/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VivendasPlanoDeAcaoRouteImport } from './routes/vivendas-plano-de-acao'
import { Route as RelatorioGeralRouteImport } from './routes/relatorio-geral'
import { Route as OutrosFollowUpsRouteImport } from './routes/outros-follow-ups'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as GerenciarRouteImport } from './routes/gerenciar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CondominioRouteImport } from './routes/$condominio'
import { Route as WebhooksNotionRouteImport } from './routes/webhooks/notion'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthGoogleStartRouteImport } from './routes/auth/google/start'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const VivendasPlanoDeAcaoRoute = VivendasPlanoDeAcaoRouteImport.update({
  id: '/vivendas-plano-de-acao',
  path: '/vivendas-plano-de-acao',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioGeralRoute = RelatorioGeralRouteImport.update({
  id: '/relatorio-geral',
  path: '/relatorio-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const OutrosFollowUpsRoute = OutrosFollowUpsRouteImport.update({
  id: '/outros-follow-ups',
  path: '/outros-follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciarRoute = GerenciarRouteImport.update({
  id: '/gerenciar',
  path: '/gerenciar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominioRoute = CondominioRouteImport.update({
  id: '/$condominio',
  path: '/$condominio',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksNotionRoute = WebhooksNotionRouteImport.update({
  id: '/webhooks/notion',
  path: '/webhooks/notion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthGoogleStartRoute = AuthGoogleStartRouteImport.update({
  id: '/auth/google/start',
  path: '/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/$condominio': typeof CondominioRoute
  '/admin': typeof AdminRoute
  '/gerenciar': typeof GerenciarRoute
  '/mcp': typeof McpRoute
  '/outros-follow-ups': typeof OutrosFollowUpsRoute
  '/relatorio-geral': typeof RelatorioGeralRoute
  '/vivendas-plano-de-acao': typeof VivendasPlanoDeAcaoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/webhooks/notion': typeof WebhooksNotionRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/$condominio': typeof CondominioRoute
  '/admin': typeof AdminRoute
  '/gerenciar': typeof GerenciarRoute
  '/mcp': typeof McpRoute
  '/outros-follow-ups': typeof OutrosFollowUpsRoute
  '/relatorio-geral': typeof RelatorioGeralRoute
  '/vivendas-plano-de-acao': typeof VivendasPlanoDeAcaoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/webhooks/notion': typeof WebhooksNotionRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$condominio': typeof CondominioRoute
  '/admin': typeof AdminRoute
  '/gerenciar': typeof GerenciarRoute
  '/mcp': typeof McpRoute
  '/outros-follow-ups': typeof OutrosFollowUpsRoute
  '/relatorio-geral': typeof RelatorioGeralRoute
  '/vivendas-plano-de-acao': typeof VivendasPlanoDeAcaoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/webhooks/notion': typeof WebhooksNotionRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$condominio'
    | '/admin'
    | '/gerenciar'
    | '/mcp'
    | '/outros-follow-ups'
    | '/relatorio-geral'
    | '/vivendas-plano-de-acao'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/logout'
    | '/webhooks/notion'
    | '/.mcp/invoke-tool/$tool'
    | '/auth/google/callback'
    | '/auth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$condominio'
    | '/admin'
    | '/gerenciar'
    | '/mcp'
    | '/outros-follow-ups'
    | '/relatorio-geral'
    | '/vivendas-plano-de-acao'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/logout'
    | '/webhooks/notion'
    | '/.mcp/invoke-tool/$tool'
    | '/auth/google/callback'
    | '/auth/google/start'
  id:
    | '__root__'
    | '/$condominio'
    | '/admin'
    | '/gerenciar'
    | '/mcp'
    | '/outros-follow-ups'
    | '/relatorio-geral'
    | '/vivendas-plano-de-acao'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/logout'
    | '/webhooks/notion'
    | '/.mcp/invoke-tool/$tool'
    | '/auth/google/callback'
    | '/auth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CondominioRoute: typeof CondominioRoute
  AdminRoute: typeof AdminRoute
  GerenciarRoute: typeof GerenciarRoute
  McpRoute: typeof McpRoute
  OutrosFollowUpsRoute: typeof OutrosFollowUpsRoute
  RelatorioGeralRoute: typeof RelatorioGeralRoute
  VivendasPlanoDeAcaoRoute: typeof VivendasPlanoDeAcaoRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  WebhooksNotionRoute: typeof WebhooksNotionRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleStartRoute: typeof AuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vivendas-plano-de-acao': {
      id: '/vivendas-plano-de-acao'
      path: '/vivendas-plano-de-acao'
      fullPath: '/vivendas-plano-de-acao'
      preLoaderRoute: typeof VivendasPlanoDeAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-geral': {
      id: '/relatorio-geral'
      path: '/relatorio-geral'
      fullPath: '/relatorio-geral'
      preLoaderRoute: typeof RelatorioGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outros-follow-ups': {
      id: '/outros-follow-ups'
      path: '/outros-follow-ups'
      fullPath: '/outros-follow-ups'
      preLoaderRoute: typeof OutrosFollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerenciar': {
      id: '/gerenciar'
      path: '/gerenciar'
      fullPath: '/gerenciar'
      preLoaderRoute: typeof GerenciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$condominio': {
      id: '/$condominio'
      path: '/$condominio'
      fullPath: '/$condominio'
      preLoaderRoute: typeof CondominioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/notion': {
      id: '/webhooks/notion'
      path: '/webhooks/notion'
      fullPath: '/webhooks/notion'
      preLoaderRoute: typeof WebhooksNotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/start': {
      id: '/auth/google/start'
      path: '/auth/google/start'
      fullPath: '/auth/google/start'
      preLoaderRoute: typeof AuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CondominioRoute: CondominioRoute,
  AdminRoute: AdminRoute,
  GerenciarRoute: GerenciarRoute,
  McpRoute: McpRoute,
  OutrosFollowUpsRoute: OutrosFollowUpsRoute,
  RelatorioGeralRoute: RelatorioGeralRoute,
  VivendasPlanoDeAcaoRoute: VivendasPlanoDeAcaoRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  WebhooksNotionRoute: WebhooksNotionRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleStartRoute: AuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
